### PR TITLE
Add replace into composer.json

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
ping @TomasVotruba

**Comment by TomasVotruba** [comment]
Will this work for CodeSniffer 2.7 or it doesn't matter?

**Comment by enumag** [comment]
I'm not sure. It might but it might not. I don't think it matters though - for code sniffer 2.7 there is no reason to use this fork instead of the original - in fact I think you should remove the older tags from this repo.

**Comment by TomasVotruba** [comment]
Yea, but I need to accept this library by packages that depend on version 2.7.
So that Sniff class namespace suites. The rest is not needed.

Will try and we'll see, that would be the best :)

Thanks for the PR!

**Pull request merged**
